
const FETCH_DATA = 'Contentful/FETCH_DATA';
const FETCH_DATA_PENDING = 'Contentful/FETCH_DATA_PENDING';
const FETCH_DATA_FULFILLED = 'Contentful/FETCH_DATA_FULFILLED';
const FETCH_DATA_REJECTED = 'Contentful/FETCH_DATA_REJECTED';

module.exports = {
	FETCH_DATA,
	FETCH_DATA_PENDING,
	FETCH_DATA_FULFILLED,
	FETCH_DATA_REJECTED
};
