
const SYNC = 'Contentful/SYNC';
const SYNC_PENDING = 'Contentful/SYNC_PENDING';
const FETCH_DATA_FULFILLED = 'Contentful/FETCH_DATA_FULFILLED';
const FETCH_DATA_REJECTED = 'Contentful/FETCH_DATA_REJECTED';

module.exports = {
	SYNC,
	SYNC_PENDING,
	FETCH_DATA_FULFILLED,
	FETCH_DATA_REJECTED
};
